### ISSUE TITLE
Mac環境でKUSANAGI_DIRにスペースが含まれていると失敗する

### ISSUE THREAD

**Issue by tao-s** [prime-strategy/kusanagi-docker#10]
# 環境
- MacBook Air (M1, 2020) 11.5.2
- Docker Desktop Version 3.5.2 (3.5.2.18)
- Docker version 20.10.7, build f0df350
- docker-compose version 1.29.2, build 5becea4c
- docker-machine version 0.16.2, build bd45ab13
- kusanagi-docker v1.2.0

**Comment by s-miyaza** [comment]
遅くなりました。kusanagi-docker 1.3.0 で、この問題に対応しました。ご確認ください。
